name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: schema-version
    attributes:
      label: Schema Version
      description: What version of our schema are you running?
      placeholder: v0.0.1
    validations:
        required: true    
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
    validations:
      required: true      
  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: Please copy and paste any relevant code or examples. This will be automatically formatted into code, so no need for backticks.
      render: Swift   
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell 
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/wwt/WorkflowSchema/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
      - label: I agree to follow this project's Code of Conduct
        required: true
