name: Feature Request
description: Suggest an idea for this project
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature!
  - type: textarea
    id: problem
    attributes:
      label: What prompted this feature request?
      description: Is your feature request related to a problem? Please describe.
      placeholder: I get frustrated every time <x> happens, it interrupts my workflow
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional ontext
      description: Add any other context or screenshots about the feature request here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/wwt/WorkflowSchema/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
