name: Version Bump

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  get_bump_level:
    if: ${{ github.repository == 'wwt/WorkflowSchema' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    outputs:
      bump_level: ${{ steps.step1.outputs.bump_level }}
    steps:
      - id: step1
        run: |
          BUMP_LEVEL=$(gh pr \
                        -R $OWNER/$REPO view $PR_NUMBER \
                        --json labels)
          major_level=$(echo $BUMP_LEVEL | jq '.labels[] | select(.name == "major").name')
          minor_level=$(echo $BUMP_LEVEL | jq '.labels[] | select(.name == "minor").name')
          patch_level=$(echo $BUMP_LEVEL | jq '.labels[] | select(.name == "patch").name')

          if [[ ! -z $major_level ]]; then
              echo "it's major"
              echo "::set-output name=bump_level::major"
          elif [[ ! -z $minor_level ]]; then
              echo "it's minor"
              echo "::set-output name=bump_level::minor"
          elif [[ ! -z $patch_level ]]; then
              echo "it's patch"
              echo "::set-output name=bump_level::patch"
          else
              echo "no level"
              echo "::set-output name=bump_level::false"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
  version_bump:
    runs-on: ubuntu-latest
    needs: get_bump_level
    env:
      working-directory: .github
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_PAT }}
      - name: Bump version and push tag
        if: needs.get_bump_level.outputs.bump_level != 'false'
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ needs.get_bump_level.outputs.bump_level }}
      - name: Build Changelog
        if: needs.get_bump_level.outputs.bump_level != 'false'
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1.7.3
        with:
          configuration: ".github/changelog_configuration.json"
          ignorePreReleases: "false"
          toTag: ${{ steps.tag_version.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        if: needs.get_bump_level.outputs.bump_level != 'false'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          token: ${{ secrets.RELEASE_PAT }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{steps.build_changelog.outputs.changelog}}
