name: Version Bump

on:
  workflow_dispatch:
  pull_request:
    branches: [ set-up-actions ]
    types: [closed]

jobs:
  get_bump_level:
    if: ${{ github.repository == 'wwt/WorkflowSchema' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    outputs:
      bump_level: ${{ steps.step1.outputs.bump_level }}
    steps:
      - id: step1
        run: |
          BUMP_LEVEL=$(gh pr \
                        -R $OWNER/$REPO view $PR_NUMBER \
                        --json labels \
                        --jq '.labels[]
                              | select(.name == "minor" or .name == "major")
                              | .name')
          if [[ ! -z $BUMP_LEVEL && ( $BUMP_LEVEL -eq "minor" || $BUMP_LEVEL -eq "major" ) ]]; then
              echo "bumping to $BUMP_LEVEL"
          else
              BUMP_LEVEL=patch
          fi
          echo "::set-output name=bump_level::$BUMP_LEVEL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
  version_bump:
    if: ${{ github.repository == 'wwt/WorkflowSchema' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    needs: get_bump_level
    env:
      working-directory: .github
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_PAT }}
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: set-up-actions
          default_bump: ${{ needs.get_bump_level.outputs.bump_level }}
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1.7.3
        with:
          configuration: ".github/changelog_configuration.json"
          ignorePreReleases: "false"
          toTag: ${{ steps.tag_version.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          token: ${{ secrets.RELEASE_PAT }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{steps.build_changelog.outputs.changelog}}
